# Generated by Django 5.2.6 on 2025-09-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Seller'), (3, 'User')], verbose_name='user_type'),
        ),
    ]
